#!/bin/sh
# 0 for not plotting
# 1 for plotting using gnuplot
plot=0

# 0 for rectangular bbox in lat/long
# 1 for rectangular bbox in crs
rect_in_crs=0

# target coordinate reference system
crs=

# one line segment on each side by default
n=1

while [ $# -ne 0 ]; do
	case $1 in
	-*)
		for i in $(echo " $1" | sed 's/-//g; s/\(.\)/\1\n/g'); do
			case $i in
			p)
				plot=1
				;;
			r)
				rect_in_crs=1
				;;
			n)
				shift
				err=1
				if [ $(echo "0$1" | sed 's/[^0-9]//g') = "0$1" ]; then
					n=$(echo $1 | sed 's/^0*\|[^0-9]//g')
					if [ "$n" != "" ]; then
						err=0
					fi
				fi
				if [ $err -eq 1 ]; then
					echo "-n option must be a positive integer"
					exit 1
				fi
				;;
			esac
		done
		;;
	*)
		if [ "$crs" = "" ]; then
			crs=$1
		fi
		;;
	esac
	shift
done

if [ "$crs" = "" ]; then
	cat<<EOT
Usage: bbox [-p] [-r] [-n N] crs

Prints bbox coordinates in the specified coordinate reference system; bbox is
assumed to be rectangular in lat/long.

 -p	Plot bbox using gnuplot
 -r	Assume a rectangular bbox in the specified coordinate reference system
	and print bbox coordinates in lat/long
 -n N	Number of line segments on each side; 1 by default
 crs	Coordinate reference system
 n	Number of line segments on each side of bbox
EOT
	exit
fi

if [ $rect_in_crs -eq 1 ]; then
	bbox_crs=$crs
	out_crs=epsg:4326
	gnuplot_using=2:1
else
	bbox_crs=epsg:4326
	out_crs=$crs
	gnuplot_using=1:2
fi

projinfo $crs |
sed '/BBOX/!d; s/^.*\[\|[][]//g; s/,/ /g' |
xargs -n 2 |
((test $rect_in_crs -eq 1 && cs2cs epsg:4236 $crs ) || cat) |
awk -v n=$n '{
	if(NR==1){
		llx=$1
		lly=$2
	}else{
		urx=$1
		ury=$2
	}
}
END{
	for(i=0; i<=n; i++){
		x=llx
		y=lly+(ury-lly)/n*i
		printf "%f %f\n", x, y
	}
	for(i=1; i<=n; i++){
		x=llx+(urx-llx)/n*i
		y=ury
		printf "%f %f\n", x, y
	}
	for(i=1; i<=n; i++){
		x=urx
		y=ury+(lly-ury)/n*i
		printf "%f %f\n", x, y
	}
	for(i=1; i<=n; i++){
		x=urx+(llx-urx)/n*i
		y=lly
		printf "%f %f\n", x, y
	}
}' |
cs2cs -f %f $bbox_crs $out_crs |
sed 's/ 0\.0*$//' |
((test $plot -eq 1 && gnuplot -p -e "plot '/dev/stdin' using $gnuplot_using with line") || cat)
